package com.demo.beans;
// Generated 25 Jun, 2017 5:24:34 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "customerdemo")
public class Users implements java.io.Serializable {

	private String name;
	private String pass;

	public Users() {
	}

	public Users(String name) {
		this.name = name;
	}

	public Users(String name, String pass) {
		this.name = name;
		this.pass = pass;
	}

	@Id

	@Column(name = "name", unique = true, nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "pass", length = 20)
	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

}
